name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions: {}

jobs:
  commitlint:
    name: Lint commits and PR title
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone the code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version-file: go.mod

      - name: Lint PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: printf '%s\n' "$PR_TITLE" | hack/commitlint.sh

      - name: Lint commits
        run: >
          hack/commitlint.sh
          --from ${{ github.event.pull_request.base.sha }}
          --to ${{ github.event.pull_request.head.sha }}
